# Generated by Django 4.2.17 on 2026-03-11 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('provider_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('patient_profile_id', models.UUIDField(blank=True, null=True)),
                ('agency_service_id', models.UUIDField(blank=True, null=True)),
                ('service_category_id', models.UUIDField(blank=True, null=True)),
                ('address_id', models.UUIDField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization_required', models.JSONField(blank=True, default=list)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('add_ons', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('patient_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('preferred_shift', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('converted', 'Converted to Booking'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('agency_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
