# Generated by Django 4.2.17 on 2026-03-11 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('nursing', 'Nursing'), ('physiotherapy', 'Physiotherapy'), ('caregiver', 'Caregiver'), ('baby_care', 'Baby Care'), ('companion', 'Companion'), ('domestic', 'Domestic Help'), ('medical_equipment', 'Medical Equipment')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conditions_served', models.JSONField(blank=True, default=list)),
                ('equipment_suggestions', models.JSONField(blank=True, default=list)),
                ('assigned_staff', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='services.servicecategory')),
            ],
        ),
    ]
