# Generated by Django 4.2.17 on 2026-03-11 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_manager', 'Admin Manager'), ('verification_officer', 'Verification Officer'), ('finance_admin', 'Finance Admin'), ('support_agent', 'Support Agent'), ('content_manager', 'Content Manager'), ('patient', 'Patient'), ('agency_admin', 'Agency Admin'), ('agency_ops', 'Agency Ops'), ('agency_booking', 'Agency Booking'), ('agency_support', 'Agency Support'), ('agency_recruiter', 'Agency Recruiter'), ('agency_finance', 'Agency Finance'), ('provider', 'Provider'), ('vendor_admin', 'Vendor Admin'), ('vendor_catalogue', 'Vendor Catalogue'), ('vendor_inventory', 'Vendor Inventory'), ('vendor_orders', 'Vendor Orders'), ('vendor_finance', 'Vendor Finance'), ('store_admin', 'Store Admin'), ('store_counter', 'Store Counter'), ('store_inventory', 'Store Inventory'), ('store_dispatch', 'Store Dispatch'), ('hospital_admin', 'Hospital Admin'), ('hospital_procurement', 'Hospital Procurement'), ('hospital_discharge', 'Hospital Discharge'), ('hospital_nursing', 'Hospital Nursing')], max_length=50)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'tenant_id')},
            },
        ),
    ]
