# Generated by Django 4.2.17 on 2026-03-11 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyPartnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('store_tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(blank=True, null=True)),
                ('file_url', models.URLField()),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prescribed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('reuse_allowed', models.BooleanField(default=False)),
                ('reuse_count', models.IntegerField(default=0)),
                ('max_reuse', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('store_tenant_id', models.UUIDField(db_index=True)),
                ('booking_id', models.UUIDField(blank=True, null=True)),
                ('patient_user_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacypartnership')),
            ],
        ),
    ]
